from tkinter import *
def open_f():
    x = open(file.get(),'r')
    txt.insert(1.0,x.read())
    x.close()
def save_f():
    x = open(file.get(),'w')
    x.write(txt.get(1.0,END))
    txt.delete(1.0,END)
    file.delete(0,END)
    x.close()
root = Tk()
f_top = Frame(root)
f_bot = Frame(root)
file = Entry(f_top,width = 20)
button_1 = Button(f_top,text = 'открыть',width=10,height = 2,command = open_f)
button_2 = Button(f_top,text = 'сохранить',width=10,height = 2,command = save_f)
txt = Text(f_bot,width = 400, height = 300,wrap = WORD)
f_top.pack()
f_bot.pack()
file.pack(side = 'right')
button_1.pack(side = 'left')
button_2.pack(side = 'left')
txt.pack(side = 'right')
root.mainloop()